#############################################################################
# Makefile for building: bin/debug/osxinj
# Generated by qmake (3.0) (Qt 5.1.0) on: Wed Aug 7 15:27:34 2013
# Project:  osxinj.pro
# Template: app
# Command: /usr/local/Qt-5.1.0/bin/qmake -spec macx-clang-32 -config debug -o Makefile osxinj.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DENV32 -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -arch i386 -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -arch i386 -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/local/Qt-5.1.0/mkspecs/macx-clang-32 -I. -Iinc -I/usr/local/Qt-5.1.0/include -I/usr/local/Qt-5.1.0/include/QtGui -I/usr/local/Qt-5.1.0/lib/QtGui.framework/Versions/5/Headers -I/usr/local/Qt-5.1.0/include/QtCore -I/usr/local/Qt-5.1.0/lib/QtCore.framework/Versions/5/Headers -Ibuild/mocfiles -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/usr/local/Qt-5.1.0/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -arch i386 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/usr/local/Qt-5.1.0/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /usr/local/Qt-5.1.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/objfiles/

####### Files

SOURCES       = main.cpp \
		inc/mach_inject/mach_inject.c \
		injector.cpp 
OBJECTS       = build/objfiles/main.o \
		build/objfiles/mach_inject.o \
		build/objfiles/injector.o
DIST          = /usr/local/Qt-5.1.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/qdevice.pri \
		/usr/local/Qt-5.1.0/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.1.0/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/unix.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/mac.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/macx.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/clang.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/clang-mac.conf \
		/usr/local/Qt-5.1.0/mkspecs/qconfig.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_clucene.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_v8.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.1.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.1.0/mkspecs/macx-clang-32/qmake.conf \
		/usr/local/Qt-5.1.0/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/usr/local/Qt-5.1.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/unix/default_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/c++11.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/qt.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/resources.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/moc.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/rez.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/lex.prf \
		osxinj.pro \
		osxinj.pro
QMAKE_TARGET  = osxinj
DESTDIR       = bin/debug/#avoid trailing-slash linebreak
TARGET        = bin/debug/osxinj

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-arch \
		i386 \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d bin/debug/ || mkdir -p bin/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: osxinj.pro .qmake.cache /usr/local/Qt-5.1.0/mkspecs/macx-clang-32/qmake.conf /usr/local/Qt-5.1.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/qdevice.pri \
		/usr/local/Qt-5.1.0/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.1.0/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/unix.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/mac.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/macx.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/clang.conf \
		/usr/local/Qt-5.1.0/mkspecs/common/clang-mac.conf \
		/usr/local/Qt-5.1.0/mkspecs/qconfig.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_clucene.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_v8.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.1.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.1.0/mkspecs/macx-clang-32/qmake.conf \
		/usr/local/Qt-5.1.0/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/usr/local/Qt-5.1.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/unix/default_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/c++11.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/qt.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/resources.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/moc.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/mac/rez.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.1.0/mkspecs/features/lex.prf \
		osxinj.pro \
		/usr/local/Qt-5.1.0/lib/QtGui.framework/QtGui.prl \
		/usr/local/Qt-5.1.0/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang-32 -config debug -o Makefile osxinj.pro
/usr/local/Qt-5.1.0/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.1.0/mkspecs/qdevice.pri:
/usr/local/Qt-5.1.0/mkspecs/features/device_config.prf:
/usr/local/Qt-5.1.0/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.1.0/mkspecs/common/unix.conf:
/usr/local/Qt-5.1.0/mkspecs/common/mac.conf:
/usr/local/Qt-5.1.0/mkspecs/common/macx.conf:
/usr/local/Qt-5.1.0/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.1.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Qt-5.1.0/mkspecs/common/clang.conf:
/usr/local/Qt-5.1.0/mkspecs/common/clang-mac.conf:
/usr/local/Qt-5.1.0/mkspecs/qconfig.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_clucene.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_designercomponents.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_v8.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.1.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.1.0/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.1.0/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.1.0/mkspecs/macx-clang-32/qmake.conf:
/usr/local/Qt-5.1.0/mkspecs/features/spec_post.prf:
.qmake.cache:
/usr/local/Qt-5.1.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.1.0/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.1.0/mkspecs/features/unix/default_pre.prf:
/usr/local/Qt-5.1.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt-5.1.0/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.1.0/mkspecs/features/default_post.prf:
/usr/local/Qt-5.1.0/mkspecs/features/c++11.prf:
/usr/local/Qt-5.1.0/mkspecs/features/mac/sdk.prf:
/usr/local/Qt-5.1.0/mkspecs/features/mac/default_post.prf:
/usr/local/Qt-5.1.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt-5.1.0/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.1.0/mkspecs/features/qt.prf:
/usr/local/Qt-5.1.0/mkspecs/features/resources.prf:
/usr/local/Qt-5.1.0/mkspecs/features/moc.prf:
/usr/local/Qt-5.1.0/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.1.0/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.1.0/mkspecs/features/mac/rez.prf:
/usr/local/Qt-5.1.0/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.1.0/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.1.0/mkspecs/features/yacc.prf:
/usr/local/Qt-5.1.0/mkspecs/features/lex.prf:
osxinj.pro:
/usr/local/Qt-5.1.0/lib/QtGui.framework/QtGui.prl:
/usr/local/Qt-5.1.0/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang-32 -config debug -o Makefile osxinj.pro

qmake_all: FORCE

dist: 
	@test -d build/objfiles/osxinj1.0.0 || mkdir -p build/objfiles/osxinj1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/objfiles/osxinj1.0.0/ && $(COPY_FILE) --parents inc/mach_inject/mach_inject.h injector.h build/objfiles/osxinj1.0.0/ && $(COPY_FILE) --parents main.cpp inc/mach_inject/mach_inject.c injector.cpp build/objfiles/osxinj1.0.0/ && (cd `dirname build/objfiles/osxinj1.0.0` && $(TAR) osxinj1.0.0.tar osxinj1.0.0 && $(COMPRESS) osxinj1.0.0.tar) && $(MOVE) `dirname build/objfiles/osxinj1.0.0`/osxinj1.0.0.tar.gz . && $(DEL_FILE) -r build/objfiles/osxinj1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/objfiles/main.o: main.cpp injector.h \
		inc/mach_inject/mach_inject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objfiles/main.o main.cpp

build/objfiles/mach_inject.o: inc/mach_inject/mach_inject.c inc/mach_inject/mach_inject.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/objfiles/mach_inject.o inc/mach_inject/mach_inject.c

build/objfiles/injector.o: injector.cpp injector.h \
		inc/mach_inject/mach_inject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objfiles/injector.o injector.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

